# Generated by Django 3.0 on 2022-03-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary', models.CharField(max_length=42)),
                ('description', models.CharField(max_length=200)),
                ('auctionEndTime', models.IntegerField(default=1646947102.3197062)),
                ('numBids', models.IntegerField(default=0)),
                ('highestBid', models.FloatField(default=0)),
                ('highestBidder', models.CharField(default='0x0000000000000000000000000000000000000000', max_length=42)),
                ('completed', models.BooleanField(default=False)),
                ('auctionID', models.IntegerField(default=0)),
                ('imgShoe', models.ImageField(default='missingPictures.jpg', upload_to='shoesPics')),
            ],
        ),
    ]
