# Generated by Django 3.0 on 2022-03-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='txReceiptAuctionEnd',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='auction',
            name='auctionEndTime',
            field=models.IntegerField(default=1647080580.5109317),
        ),
    ]
